# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"

#M1 O(n) --> with extra space
def findTheDifference( s, t):
  ds, dt = {}, {}
  for i in s:
    ds[i] = ds.get(i, 0) + 1
  for i in t:
    dt[i] = dt.get(i, 0) + 1
  
  
  for k, v in dt.items():
    if k not in ds:
      return k
    if k in ds and v != ds[k]:
      return k

# M2 O(n logn) -- > extra space too
def findTheDifference2(s, t):     
    s = list(s)
    s.sort()
    s = ''.join(s)
    t = list(t)
    t.sort()
    t = ''.join(t)
    n = len(s)
    i, j = 0, 0
    diff = ''
    while i < n:
      if s[i] == t[j]:
        i += 1
        j += 1
      else:
        diff = t[j]
        j += 1
    
    return t[-1] if diff == '' else diff
          
        